#Tell Gitlab to load these environental vars from the variables list
variables:
  PYPI_USER: SECURE
  PYPI_PASS: SECURE

stages:
  - build
  - installer
  - test
  - deploy


build docs:
  stage: build
  script:
    - tox -e docs
  tags:
    - shared-linux, gui
  artifacts:
    paths:
    - doc/
    expire_in: 1 week


build linux installer:
  stage: build
  script:
    - tox -e installer
  tags:
    - shared-linux, gui
  artifacts:
    paths:
    - dist/
    expire_in: 1 week


build mac installer:
  stage: build
  script:
    - tox -e installer
  tags:
    - shared-mac, gui
  artifacts:
    paths:
    - dist/
    expire_in: 1 week


build windows installer:
  stage: build
  script:
    - tox -e installer
  tags:
    - shared-win, gui
  artifacts:
    paths:
    - dist/
    expire_in: 1 week


test Linux:
  stage: test
  variables:
    LD_LIBRARY_PATH: ${CI_PROJECT_DIR}/.tox/py36/lib/python3.6/site-packages/PySide2/Qt/plugins/platforms
    DISPLAY: localhost:1
  script:
    - echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    - echo "DISPLAY=${DISPLAY}"
    - tox
  tags:
    - shared-linux, gui
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


test macOS:
  stage: test
  script:
      - tox
  tags:
    - shared-mac, gui


test Windows:
  stage: test
  script:
      - tox
  tags:
    - shared-win, gui

deploy pip to PyPI:

  stage: deploy
  when: manual
  only:
    - tags
    
  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/scikit-surgerybard
    
  tags:
    - pip-production
    
  artifacts:
    paths:
    - dist/
    
  script:
    # Install packages required to build/publish
    # remove any previous distribution files
    - pip install wheel twine setuptools
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to pypi
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS
